- name: Install ufw for easy firewall configuration
  apt:
    name: ufw

- name: Deny everything and enable ufw
  ufw:
    state: enabled
    default: deny

- name: Allow ssh and limit retries (default 6)
  ufw:
    rule: limit
    port: "22"
    proto: tcp
