- name: update and upgrade system
  tags: maintenance
  apt:
    update_cache: yes
    upgrade: "safe"
    autoremove: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- import_tasks: setup_ansible_user.yml
  tags: setup

- import_tasks: setup_firewall.yml
  tags: [setup, firewall]