- name: create ansible group
  tags: setup
  group:
    name: ansible
    system: yes

- name: create ansible user
  user:
    name: ansible
    group: ansible

- name: add ssh key for ansible
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+MIQ6peEG+gFUEpJ+5hKib8Oqw7VDWVVhzOz8C/eu+ admin@vivi.land"

- name: add sudoers file for user ansible
  copy:
    src: etc/sudoers.d/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440