- name: update and upgrade system
  tags: maintenance
  apt:
    update_cache: yes
    upgrade: "safe"
    autoremove: yes
  changed_when: false
  when: ansible_os_family == 'Debian'

- import_tasks: setup_docker_swarm.yml
  tags: [swarm, setup]
  when: ansible_os_family == 'Debian'