- name: Install ufw for easy firewall configuration
  apt:
    name: ufw

- name: Deny everything and enable ufw
  ufw:
    state: enabled
    default: deny

- name: Allow http access
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow https access
  ufw:
    rule: allow
    port: "443"
    proto: tcp