- name: Install docker
  apt:
    name: docker.io
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install python3 pip
  apt:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install docker-py
  pip:
    name: docker-py
    state: present

- name: Init a new swarm with default parameters
  community.general.docker_swarm:
    state: absent
    force: yes